# Generated by Django 4.0.3 on 2022-04-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('Common_Name', models.CharField(max_length=100)),
                ('Scientific_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Family', models.CharField(max_length=50)),
                ('SubFamily', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='plantUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_main_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_method', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('Abundant_Area', models.CharField(max_length=1000, null=True)),
                ('Scientific_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.plant')),
            ],
        ),
    ]
