# Generated by Django 4.0.3 on 2022-04-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantupload',
            name='name',
        ),
    ]
